jobs:
  - language: node_js
    node_js:
      - '10'
    install:
      - cd src
      - npm install
    script:
      - npm run build
dist: trusty
sudo: false
cache: npm
branches:
  only:
    - develop
install:
  - cd src
  - npm install
script:
  - npm build

deploy:
  provider: s3
  access_key_id: '$AWS_ACCESS_KEY_ID'
  secret_access_key: '$AWS_SECRET_ACCESS_KEY'
  bucket: 1day-release.com
  region: ap-northeast-1
  local_dir: dist
  endpoint: 1day-release.com.s3-website-ap-northeast-1.amazonaws.com
  skip_cleanup: true
  on:
    branch: deploy

after_deploy:
  - aws s3 sync dist/. s3://1day-release.com
