language: node_js
node_js:
  - '10'
dist: trusty
sudo: false
cache: npm
branches:
  only:
    - develop
    - stating
    - master
install:
  - cd src/vue-cli3
  - npm install
script:
  - npm run build

deploy:
  - provider: s3
    access_key_id: '$AWS_ACCESS_KEY_ID'
    secret_access_key: '$AWS_SECRET_ACCESS_KEY'
    bucket: 1day-release.com
    region: ap-northeast-1
    local_dir: dist
    endpoint: s3-ap-northeast-1.amazonaws.com
    skip_cleanup: true
    on:
      branch: develop

notifications:
  slack:
    secure: 'A2DW9H4xe4GAV9JZ0OlU8IerEgDHvJk/pDTJbP3K9tXCgLmlpQjoGxYSShrxZnQUVfpFdr9P6xl99fSeDrXsiiwsIR5m7cX3T9Js0G+zQJMBzFplv3Y5roCh2v82TeiCyLSIRi3AJb332UMHOenWyuK19jtyUuwZYZ78g4QNbl31sX7BHyZp/rRVzp92coXPFLWukJcNSrDGLk3Wlt6g/AN0u+1tg9XuD+gyfbDTToHeEh9GZXaG7XGUEOFnaRTuel0H2IYyRdbFH2STCL+JjUYp3zooonifAxEap3+yjArWo4dPgYs5bkItsOP7SgSBFPgKJUzeAaY6lzwcrjXmScuUlK2Fd1fSpPFao/oaTgV1oItWGZrLDfUG9/dyOSG0tbLKkip+i+NCa9VSfgpzj6Q+LEUnLySySNAdGrCtQreAEMCt2MOu69WqRO2vrFZbQL9LW+ew4mVBwvSLXBMppxtJrBnvWTW2rgxny7edDh5BgW88EhacVpAO80Ix85UvVUaQAoOF/73ciaDG9Ms8w/hTJGiDqx+RDjm64ZCExNGIgeM09ZDanDFUeI5dCCE2rtxlIjnR2zBDdpf659jVxFVjwUiHAwN6lSWB23rCIt/KS5hjo8S3FCx3/dmRHy7HUnBrbAqUX4jtQNAL4WoNgaDm7OOD1vHOWG+cCOewHIc='
